# Generated by Django 5.0.3 on 2024-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('pid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('media_address', models.CharField(max_length=256)),
                ('likes_count', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=32, null=True)),
                ('media_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('lang', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
