# Generated by Django 5.0.3 on 2024-04-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('users', '0003_rename_uid_collabdb_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
