# Generated by Django 5.0.3 on 2024-04-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postdata_username'),
        ('users', '0004_profiledatadb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb'),
        ),
    ]
