# Generated by Django 5.0.3 on 2024-04-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postdata_pid'),
        ('users', '0018_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
