# Generated by Django 5.0.6 on 2025-02-04 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab_Information',
            fields=[
                ('collaboration_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collaboration_title', models.CharField(default='Untitled collaboration', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='media/Posts')),
                ('media_thumbnail', models.FileField(blank=True, default=None, null=True, upload_to='media/Thumbnails')),
                ('caption', models.CharField(max_length=30)),
                ('descr', models.TextField()),
                ('langu', models.CharField(max_length=15)),
                ('mediatype', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('likes', models.IntegerField(default=0)),
                ('media_format', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='profiledatadb',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(upload_to='Media/')),
                ('user_bio', models.TextField()),
                ('phone', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('yout', models.URLField(blank=True, null=True)),
                ('twit', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.collab_information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collaboration', 'user')},
            },
        ),
        migrations.AddField(
            model_name='collab_information',
            name='collaborated_members',
            field=models.ManyToManyField(through='users.Member_Information', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collab_information',
            name='base_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.postdb'),
        ),
        migrations.AddField(
            model_name='postdb',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb'),
        ),
        migrations.CreateModel(
            name='saveddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.postdb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_relation', to='users.postdb')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_relation', to='users.postdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
