# Generated by Django 5.0.3 on 2024-04-27 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiledatadb',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='Media/')),
                ('user_bio', models.TextField()),
                ('phone', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_address', models.CharField(max_length=256)),
                ('likes_count', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=32, null=True)),
                ('media_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('lang', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
        migrations.CreateModel(
            name='CollabDB',
            fields=[
                ('col_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.postdata')),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.postdata')),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
    ]
