# Generated by Django 5.0.6 on 2025-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='base_plan',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='member_information',
            name='is_owner',
            field=models.IntegerField(default=0),
        ),
    ]
