# Generated by Django 5.0.3 on 2024-04-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdatadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_address', models.CharField(max_length=256)),
                ('likes_count', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=32, null=True)),
                ('media_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('lang', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
    ]
