# Generated by Django 5.0.3 on 2024-04-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdb',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='saveddb',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
