# Generated by Django 5.0.4 on 2024-04-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postdata_pid'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabdb',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.postdata'),
        ),
        migrations.AddField(
            model_name='saveddb',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.postdata'),
        ),
        migrations.AlterField(
            model_name='collabdb',
            name='col_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
