# Generated by Django 5.0.6 on 2025-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiledatadb_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(upload_to='media/Profiles'),
        ),
    ]
