# Generated by Django 5.0.6 on 2025-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collab_information_base_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab_information',
            name='base_plan',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
