# Generated by Django 5.0.6 on 2024-10-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiledatadb_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='Media/'),
        ),
    ]
