# Generated by Django 5.0.3 on 2024-05-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_postdatadb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postdatadb',
        ),
    ]
