# Generated by Django 5.0.3 on 2024-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collabdb_pid_saveddb_pid_alter_collabdb_col_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='prof_picaddress',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
