# Generated by Django 5.0.3 on 2024-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_collabdb_uid_alter_saveddb_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabdb',
            old_name='uid',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='saveddb',
            old_name='uid',
            new_name='username',
        ),
    ]
