# Generated by Django 5.0.6 on 2025-01-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_like'),
        ('users', '0003_alter_profiledatadb_profile_picture'),
    ]

    operations = [
    ]
