# Generated by Django 5.0.3 on 2024-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_uid_collabdb_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiledatadb',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='Media/Profiles/')),
                ('user_bio', models.TextField()),
                ('phone', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
