# Generated by Django 5.0.3 on 2024-05-03 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_postdatadb'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('media', models.FileField(upload_to='media/Posts')),
                ('caption', models.CharField(max_length=15)),
                ('descr', models.TextField()),
                ('langu', models.CharField(max_length=15)),
                ('mediatype', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
            ],
        ),
    ]
