# Generated by Django 5.0.6 on 2025-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_collab_information_base_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_information',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='collab_information',
            name='collab_requestor',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='collab_information',
            name='base_plan',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='profiledatadb',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
