# Generated by Django 5.0.6 on 2025-02-21 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_information_is_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_information',
            old_name='user',
            new_name='post_owner',
        ),
        migrations.AlterUniqueTogether(
            name='member_information',
            unique_together={('collaboration', 'post_owner')},
        ),
    ]
