# Generated by Django 5.0.3 on 2024-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profiledatadb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
