# Generated by Django 5.0.3 on 2024-05-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_postdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb'),
        ),
    ]
