# Generated by Django 5.0.3 on 2024-04-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profiledatadb_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdb',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb'),
        ),
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='Media/Profiles'),
        ),
        migrations.AlterField(
            model_name='saveddb',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb'),
        ),
    ]
