# Generated by Django 5.0.6 on 2025-01-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250103_0850'),
        ('users', '0005_save'),
    ]

    operations = [
    ]
