# Generated by Django 5.0.6 on 2025-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_member_information_post_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='collab_end',
            field=models.BooleanField(default=False),
        ),
    ]
