# Generated by Django 5.0.3 on 2024-05-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_postdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='caption',
            field=models.CharField(max_length=30),
        ),
    ]
