# Generated by Django 5.0.3 on 2024-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdata_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='prof_picaddress',
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='images/profile_pictures/'),
        ),
    ]
