# Generated by Django 5.0.3 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userdata_prof_picaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='specialised',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
