# Generated by Django 5.0.6 on 2025-02-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_collab_information_collab_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab_information',
            name='collaboration_title',
            field=models.CharField(default='Untitled collaboration test', max_length=50),
        ),
    ]
