# Generated by Django 5.0.6 on 2025-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_0004_merge_20250103_0850_0005_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/dpp.png', null=True, upload_to='Media/'),
        ),
    ]
