# Generated by Django 5.0.3 on 2024-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profiledatadb_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
