# Generated by Django 5.0.3 on 2025-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profiledatadb_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(default='default/user.png', upload_to='Media/'),
        ),
    ]
