# Generated by Django 5.0.6 on 2025-02-27 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_collab_information_collaboration_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatadb',
            name='profile_picture',
            field=models.ImageField(upload_to='media/Profiles'),
        ),
        migrations.CreateModel(
            name='syncAudios',
            fields=[
                ('syncId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('syncMedia', models.FileField(upload_to='media/syncAudios')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.collab_information')),
            ],
        ),
    ]
