# Generated by Django 5.0.3 on 2024-05-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_postdb_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='media',
            field=models.FileField(upload_to='media/Posts'),
        ),
    ]
