# Generated by Django 5.0.3 on 2024-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_postdb_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
