# Generated by Django 5.0.6 on 2025-02-28 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profiledatadb_profile_picture_syncaudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncaudios',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
