# Generated by Django 5.0.6 on 2025-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_syncaudios_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='owner_count',
            field=models.IntegerField(default=1),
        ),
    ]
