# Generated by Django 5.0.4 on 2024-05-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profiledatadb_insta_profiledatadb_twit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.postdb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiledatadb')),
            ],
        ),
    ]
