# Generated by Django 5.0.3 on 2025-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='flag_status',
            field=models.CharField(blank=True, choices=[(None, 'Not Flagged'), ('copyright', 'Copyright Infringement'), ('offensive', 'Offensive/Explicit Content')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('collab', 'Collaboration Request'), ('flagged', 'Post Flagged')], max_length=10),
        ),
    ]
