# Generated by Django 5.0.3 on 2024-04-25 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_alter_collabdb_uid_alter_saveddb_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='userdata',
        ),
    ]
