# Generated by Django 5.0.6 on 2025-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_collab_information_owner_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='accept_count',
            field=models.IntegerField(default=0),
        ),
    ]
