# Generated by Django 5.0.4 on 2024-05-07 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_saveddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
