# Generated by Django 5.0.3 on 2025-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_postdb_flag_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='flag_status',
        ),
        migrations.AddField(
            model_name='postdb',
            name='flag_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postdb',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
