# Generated by Django 5.0.3 on 2025-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_collab_information_accept_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
