# Generated by Django 5.0.6 on 2025-03-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_collab_information_accept_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='isCollaborated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.postdb')),
            ],
            options={
                'unique_together': {('post_id', 'collab_members')},
            },
        ),
        migrations.AddField(
            model_name='postdb',
            name='collaborated_owners',
            field=models.ManyToManyField(through='users.collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
