# Generated by Django 5.0.4 on 2024-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_postdb_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
