# Generated by Django 5.0.6 on 2025-03-04 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_postdb_iscollaborated_collaborators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_information',
            old_name='post_owner',
            new_name='post_member',
        ),
        migrations.AlterUniqueTogether(
            name='member_information',
            unique_together={('collaboration', 'post_member')},
        ),
        migrations.AddField(
            model_name='member_information',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
