# Generated by Django 5.0.6 on 2025-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_post_owner_member_information_post_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_information',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
