# Generated by Django 5.0.3 on 2024-04-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userdata_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
