# Generated by Django 5.0.4 on 2025-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profiledatadb_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
