# Generated by Django 5.0.6 on 2025-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_member_information_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='temp_caption',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='collab_information',
            name='temp_descr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='collab_information',
            name='temp_mediaType',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collab_information',
            name='temp_thumbnail',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/Thumbnails'),
        ),
        migrations.AlterField(
            model_name='postdb',
            name='langu',
            field=models.CharField(default='English', max_length=15),
        ),
    ]
