# Generated by Django 5.0.3 on 2024-04-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
