# Generated by Django 5.0.6 on 2025-03-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_collab_information_temp_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='collaboration',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
