# Generated by Django 5.0.3 on 2024-04-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default_profile_picture.jpg', null=True, upload_to='Media/Profiles/'),
        ),
    ]
