# Generated by Django 5.0.6 on 2025-03-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_syncaudios_syncedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab_information',
            name='endPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collab_end_posts', to='users.postdb'),
        ),
        migrations.AlterField(
            model_name='collab_information',
            name='base_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_base_posts', to='users.postdb'),
        ),
    ]
