# Generated by Django 5.0.6 on 2025-03-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_collab_information_chat_history'),
        ('users', '0018_collab_information_endpost_and_more'),
    ]

    operations = [
    ]
