# Generated by Django 5.0.4 on 2024-04-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdata_profile_picture'),
        ('users', '0018_alter_profile_username'),
    ]

    operations = [
    ]
