# Generated by Django 5.0.6 on 2025-03-07 21:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20250307_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncaudios',
            name='audioName',
            field=models.CharField(default=users.models.generate_audio_name, max_length=50),
        ),
    ]
