# Generated by Django 5.0.3 on 2024-04-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='specialised',
        ),
    ]
